spacetrack.username=${DEFAULT_USERNAME}
spacetrack.password=${DEFAULT_PASSWORD}
spacetrack.baseUrl=https://www.space-track.org

home.path=.orbitlab
dataset.path=dataset
ephemeris.path=ephemeris
orbits.path=orbits
scenarios.path=scenarios
